export const STORY_WORDS_DE: readonly string[] = [
  'Dampfschiff',
  'Gummiente',
  'Zaubertrank',
  'Taschenlampe',
  'Dinosaurier',
  'Regenbogen',
  'Kaffeemaschine',
  'Astronaut',
  'Schneeball',
  'Zeitmaschine',
  'Papagei',
  'Geheimagent',
  'Bratwurst',
  'Kaugummi',
  'Piratenschiff',
  'Kristallkugel',
  'Dampflokomotive',
  'U-Boot',
  'Ritterrüstung',
  'Schatztruhe',
  'Flugzeugträger',
  'Vulkan',
  'Gartenzwerg',
  'Schlüsselbund',
  'Kompass',
  'Fledermaus',
  'Geisterhaus',
  'Roboter',
  'Sonnenschirm',
  'Kühlschrank',
  'Monokel',
  'Fernrohr',
  'Heißluftballon',
  'Feuerwerk',
  'Hängematte',
  'Kaktus',
  'Taschenuhr',
  'Waffeleisen',
  'Schaukelstuhl',
  'Laterne',
  'Schneekugel',
  'Gitarre',
  'Perücke',
  'Dudelsack',
  'Fallschirm',
  'Labyrinth',
  'Mikroskop',
  'Schokoladentafel',
  'Drachenei',
  'Zauberstab',
];

export const STORY_WORDS_EN: readonly string[] = [
  'steamboat',
  'rubber duck',
  'magic potion',
  'flashlight',
  'dinosaur',
  'rainbow',
  'coffee maker',
  'astronaut',
  'snowball',
  'time machine',
  'parrot',
  'secret agent',
  'sausage',
  'bubblegum',
  'pirate ship',
  'crystal ball',
  'steam train',
  'submarine',
  'knight armor',
  'treasure chest',
  'aircraft carrier',
  'volcano',
  'garden gnome',
  'keychain',
  'compass',
  'bat',
  'haunted house',
  'robot',
  'parasol',
  'refrigerator',
  'monocle',
  'telescope',
  'hot air balloon',
  'fireworks',
  'hammock',
  'cactus',
  'pocket watch',
  'waffle iron',
  'rocking chair',
  'lantern',
  'snow globe',
  'guitar',
  'wig',
  'bagpipes',
  'parachute',
  'labyrinth',
  'microscope',
  'chocolate bar',
  'dragon egg',
  'magic wand',
];

export const getRandomWords = (
  language: string,
  count = 3,
  excludeWords: string[] = [],
): string[] => {
  const pool = language.toLowerCase().startsWith('de') ? STORY_WORDS_DE : STORY_WORDS_EN;
  const available = pool.filter(
    (w) => !excludeWords.map((e) => e.toLowerCase()).includes(w.toLowerCase()),
  );
  const source = available.length >= count ? available : pool;
  const shuffled = [...source].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};
