import type { WordPair } from './wordPairCategories';

/**
 * German word pairs with category assignments.
 * Each pair can belong to multiple categories.
 */
export const WORD_PAIRS_DE: WordPair[] = [
    // Food & Drinks
    { words: ['Pizza', 'Burger'], categoryIds: ['food_drinks'] },
    { words: ['Kaffee', 'Tee'], categoryIds: ['food_drinks'] },
    { words: ['Sushi', 'Pizza'], categoryIds: ['food_drinks'] },
    { words: ['Hamburger', 'Hotdog'], categoryIds: ['food_drinks'] },
    { words: ['Schokolade', 'Vanille'], categoryIds: ['food_drinks'] },
    { words: ['Bier', 'Wein'], categoryIds: ['food_drinks'] },
    { words: ['Whiskey', 'Wodka'], categoryIds: ['food_drinks'] },
    { words: ['Milch', 'Saft'], categoryIds: ['food_drinks'] },
    { words: ['Brot', 'Butter'], categoryIds: ['food_drinks'] },
    { words: ['Reis', 'Nudeln'], categoryIds: ['food_drinks'] },
    { words: ['Hühnchen', 'Rindfleisch'], categoryIds: ['food_drinks'] },
    { words: ['Salz', 'Pfeffer'], categoryIds: ['food_drinks'] },
    { words: ['Zucker', 'Honig'], categoryIds: ['food_drinks'] },
    { words: ['Wasser', 'Limonade'], categoryIds: ['food_drinks'] },
    { words: ['Pfannkuchen', 'Donut'], categoryIds: ['food_drinks'] },
    { words: ['Eiscreme', 'Kuchen'], categoryIds: ['food_drinks'] },
    { words: ['Pizza', 'Pasta'], categoryIds: ['food_drinks'] },
    { words: ['Pizza', 'Lasagne'], categoryIds: ['food_drinks'] },
    { words: ['Tortilla', 'Taco'], categoryIds: ['food_drinks'] },
    { words: ['Baguette', 'Ciabatta'], categoryIds: ['food_drinks'] },
    { words: ['Hot Dog', 'Bratwurst'], categoryIds: ['food_drinks'] },
    { words: ['Energy Drink', 'Limonade'], categoryIds: ['food_drinks'] },
    { words: ['Kokosmilch', 'Sojamilch'], categoryIds: ['food_drinks'] },
    { words: ['Brot', 'Toast'], categoryIds: ['food_drinks'] },

    // Nature & Animals
    { words: ['Hund', 'Katze'], categoryIds: ['nature_animals'] },
    { words: ['Strand', 'Berg'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Sonne', 'Mond'], categoryIds: ['nature_animals'] },
    { words: ['Banane', 'Apfel'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Apfel', 'Orange'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Banane', 'Erdbeere'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Karotte', 'Brokkoli'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Kartoffel', 'Tomate'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Zwiebel', 'Knoblauch'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Hund', 'Wolf'], categoryIds: ['nature_animals'] },
    { words: ['Apfel', 'Birne'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Maus', 'Ratte'], categoryIds: ['nature_animals'] },
    { words: ['Gurke', 'Zucchini'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Erdbeere', 'Himbeere'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Banane', 'Kochbanane'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Kokosnuss', 'Ananas'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Drache', 'Dinosaurier'], categoryIds: ['nature_animals', 'entertainment'] },
    { words: ['Vulkan', 'Berg'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Wüste', 'Sand'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Wolke', 'Nebel'], categoryIds: ['nature_animals'] },
    { words: ['Schnee', 'Hagel'], categoryIds: ['nature_animals'] },
    { words: ['Dschungel', 'Wald'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Papagei', 'Krähe'], categoryIds: ['nature_animals'] },
    { words: ['Fledermaus', 'Eule'], categoryIds: ['nature_animals'] },
    { words: ['Wolf', 'Fuchs'], categoryIds: ['nature_animals'] },
    { words: ['Fluss', 'See'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Ozean', 'Fluss'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Tiger', 'Gepard'], categoryIds: ['nature_animals'] },
    { words: ['Hai', 'Delfin'], categoryIds: ['nature_animals'] },
    { words: ['Pinguin', 'Möwe'], categoryIds: ['nature_animals'] },
    { words: ['Mond', 'Planet'], categoryIds: ['nature_animals'] },
    { words: ['Komet', 'Asteroid'], categoryIds: ['nature_animals'] },
    { words: ['See', 'Teich'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Giraffe', 'Zebra'], categoryIds: ['nature_animals'] },
    { words: ['Elefant', 'Nashorn'], categoryIds: ['nature_animals'] },
    { words: ['Skorpion', 'Spinne'], categoryIds: ['nature_animals'] },
    { words: ['Tintenfisch', 'Oktopus'], categoryIds: ['nature_animals'] },
    { words: ['Qualle', 'Tintenfisch'], categoryIds: ['nature_animals'] },
    { words: ['Birke', 'Strauch'], categoryIds: ['nature_animals'] },
    { words: ['Brunnen', 'Wasserfall'], categoryIds: ['nature_animals', 'places'] },

    // Technology
    { words: ['Apple', 'Microsoft'], categoryIds: ['technology', 'brands'] },
    { words: ['Google', 'Facebook'], categoryIds: ['technology', 'brands'] },
    { words: ['Amazon', 'Netflix'], categoryIds: ['technology', 'brands', 'entertainment'] },
    { words: ['Laptop', 'Tablet'], categoryIds: ['technology'] },
    { words: ['Bitcoin', 'Ethereum'], categoryIds: ['technology'] },
    { words: ['Facebook', 'Instagram'], categoryIds: ['technology', 'brands'] },
    { words: ['iPhone', 'Samsung'], categoryIds: ['technology', 'brands'] },
    { words: ['PlayStation', 'Xbox'], categoryIds: ['technology', 'games'] },
    { words: ['Windows', 'MacOS'], categoryIds: ['technology'] },
    { words: ['YouTube', 'TikTok'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Twitch', 'Kick'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Spotify', 'Apple Music'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Reddit', 'Discord'], categoryIds: ['technology'] },
    { words: ['Instagram', 'Snapchat'], categoryIds: ['technology', 'brands'] },
    { words: ['ChatGPT', 'Gemini'], categoryIds: ['technology'] },
    { words: ['Laptop', 'Desktop'], categoryIds: ['technology'] },
    { words: ['Tablet', 'Smartphone'], categoryIds: ['technology'] },
    { words: ['Maus', 'Tastatur'], categoryIds: ['technology'] },
    { words: ['Fernseher', 'Laptop'], categoryIds: ['technology'] },
    { words: ['Mikrofon', 'Kamera'], categoryIds: ['technology'] },
    { words: ['Twitch', 'Netflix'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Twitter', 'Facebook'], categoryIds: ['technology', 'brands'] },
    { words: ['SpaceX', 'Tesla'], categoryIds: ['technology', 'brands'] },

    // Brands & Companies
    { words: ['Parfüm', 'Deo'], categoryIds: ['brands', 'general'] },
    { words: ['Adidas', 'Nike'], categoryIds: ['brands', 'sports'] },
    { words: ['McDonalds', 'KFC'], categoryIds: ['brands', 'food_drinks'] },
    { words: ['Burger King', 'McDonald\'s'], categoryIds: ['brands', 'food_drinks'] },
    { words: ['Sony', 'Samsung'], categoryIds: ['brands', 'technology'] },
    { words: ['Mercedes', 'BMW'], categoryIds: ['brands'] },
    { words: ['Tesla', 'Porsche'], categoryIds: ['brands'] },
    { words: ['Ferrari', 'Lamborghini'], categoryIds: ['brands'] },
    { words: ['Coca-Cola', 'Pepsi'], categoryIds: ['brands', 'food_drinks'] },


    // Sports
    { words: ['Fußball', 'Basketball'], categoryIds: ['sports'] },
    { words: ['Fußball', 'Rugby'], categoryIds: ['sports'] },
    { words: ['Tennis', 'Badminton'], categoryIds: ['sports'] },
    { words: ['Skifahren', 'Schnee'], categoryIds: ['sports', 'nature_animals'] },
    { words: ['Schwimmen', 'Tauchen'], categoryIds: ['sports'] },
    { words: ['Laufen', 'Joggen'], categoryIds: ['sports'] },
    { words: ['Fahrrad', 'Motorrad'], categoryIds: ['sports', 'general'] },
    { words: ['Boxen', 'Karate'], categoryIds: ['sports'] },
    { words: ['Hockey', 'Fußball'], categoryIds: ['sports'] },
    { words: ['Bowling', 'Golf'], categoryIds: ['sports'] },
    { words: ['Marathon', 'Sprint'], categoryIds: ['sports'] },
    { words: ['Fechten', 'Bogenschießen'], categoryIds: ['sports'] },
    { words: ['Volleyball', 'Basketball'], categoryIds: ['sports'] },
    { words: ['Tischtennis', 'Badminton'], categoryIds: ['sports'] },
    { words: ['Baseball', 'Football'], categoryIds: ['sports'] },
    { words: ['Surfbrett', 'Skateboard'], categoryIds: ['sports'] },
    { words: ['Golf', 'Cricket'], categoryIds: ['sports'] },
    { words: ['UFC', 'WWE'], categoryIds: ['sports', 'entertainment'] },
    { words: ['Olympia', 'WM'], categoryIds: ['sports'] },
    { words: ['NBA', 'NFL'], categoryIds: ['sports'] },
    { words: ['Bayern München', 'Real Madrid'], categoryIds: ['sports'] },

    // Entertainment
    { words: ['Herr der Ringe', 'Der Hobbit'], categoryIds: ['entertainment'] },
    { words: ['Harry Potter', 'Lord Voldemort'], categoryIds: ['entertainment'] },
    { words: ['Superman', 'Batman'], categoryIds: ['entertainment'] },
    { words: ['Spiderman', 'Ironman'], categoryIds: ['entertainment'] },
    { words: ['Captain America', 'Thor'], categoryIds: ['entertainment'] },
    { words: ['Musik', 'Tanzen'], categoryIds: ['entertainment'] },
    { words: ['Geist', 'Zombie'], categoryIds: ['entertainment'] },
    { words: ['Ballett', 'Hip Hop'], categoryIds: ['entertainment'] },
    { words: ['Radio', 'Podcast'], categoryIds: ['entertainment', 'technology'] },
    { words: ['Online Nachrichten', 'Zeitung'], categoryIds: ['entertainment'] },
    { words: ['Konzert', 'Festival'], categoryIds: ['entertainment'] },
    { words: ['Netflix', 'Kino'], categoryIds: ['entertainment'] },
    { words: ['Game of Thrones', 'Herr der Ringe'], categoryIds: ['entertainment'] },
    { words: ['Star Wars', 'Star Trek'], categoryIds: ['entertainment'] },
    { words: ['Harry Potter', 'Percy Jackson'], categoryIds: ['entertainment'] },
    { words: ['Sherlock Holmes', 'Hercule Poirot'], categoryIds: ['entertainment'] },
    { words: ['Dracula', 'Frankenstein'], categoryIds: ['entertainment'] },
    { words: ['James Bond', 'Geheimdienst'], categoryIds: ['entertainment'] },
    { words: ['Homer Simpson', 'Peter Griffin'], categoryIds: ['entertainment'] },
    { words: ['SpongeBob', 'Patrick'], categoryIds: ['entertainment'] },
    { words: ['Godzilla', 'King Kong'], categoryIds: ['entertainment'] },
    { words: ['Techno', 'Rap'], categoryIds: ['entertainment'] },
    { words: ['Rock', 'Pop'], categoryIds: ['entertainment'] },
    { words: ['Roman', 'Gedicht'], categoryIds: ['entertainment'] },
    { words: ['Enzyklopädie', 'Wörterbuch'], categoryIds: ['entertainment', 'general'] },
    { words: ['Thor', 'Blitz'], categoryIds: ['entertainment'] },
    { words: ['Obi Wan', 'Macht'], categoryIds: ['entertainment'] },

    // Famous People
    { words: ['Einstein', 'Newton'], categoryIds: ['famous_people'] },
    { words: ['Elvis', 'The Beatles'], categoryIds: ['famous_people', 'entertainment'] },
    { words: ['Leonardo da Vinci', 'Michelangelo'], categoryIds: ['famous_people'] },
    { words: ['Napoleon', 'Cäsar'], categoryIds: ['famous_people'] },
    { words: ['Hitler', 'Stalin'], categoryIds: ['famous_people'] },
    { words: ['Picasso', 'Van Gogh'], categoryIds: ['famous_people'] },
    { words: ['Mozart', 'Beethoven'], categoryIds: ['famous_people', 'entertainment'] },
    { words: ['Messi', 'Ronaldo'], categoryIds: ['famous_people', 'sports'] },

    // Games
    { words: ['Mario', 'Luigi'], categoryIds: ['games', 'entertainment'] },
    { words: ['Sonic', 'Tails'], categoryIds: ['games', 'entertainment'] },
    { words: ['Pac-Man', 'Tetris'], categoryIds: ['games'] },
    { words: ['Fortnite', 'Minecraft'], categoryIds: ['games'] },
    { words: ['Call of Duty', 'Battlefield'], categoryIds: ['games'] },
    { words: ['Lego', 'Playmobil'], categoryIds: ['games'] },
    { words: ['UNO', 'Monopoly'], categoryIds: ['games'] },
    { words: ['Catan', 'Risiko'], categoryIds: ['games'] },
    { words: ['Blackjack', 'Poker'], categoryIds: ['games'] },
    { words: ['Bingo', 'Roulette'], categoryIds: ['games'] },
    { words: ['Puzzle', 'Kreuzworträtsel'], categoryIds: ['games'] },
    { words: ['Kartenspiel', 'Würfel'], categoryIds: ['games'] },

    // Places
    { words: ['New York', 'Los Angeles'], categoryIds: ['places'] },
    { words: ['Paris', 'London'], categoryIds: ['places'] },
    { words: ['Rom', 'Athen'], categoryIds: ['places'] },
    { words: ['Sydney', 'Melbourne'], categoryIds: ['places'] },
    { words: ['Rio de Janeiro', 'Buenos Aires'], categoryIds: ['places'] },
    { words: ['Mount Everest', 'Nepal'], categoryIds: ['places'] },
    { words: ['Amazonas', 'Nil'], categoryIds: ['places', 'nature_animals'] },
    { words: ['Grand Canyon', 'Niagarafälle'], categoryIds: ['places'] },
    { words: ['Taj Mahal', 'Chinesische Mauer'], categoryIds: ['places'] },
    { words: ['Eiffelturm', 'Freiheitsstatue'], categoryIds: ['places'] },
    { words: ['Big Ben', 'Schiefer Turm von Pisa'], categoryIds: ['places'] },
    { words: ['Japan', 'China'], categoryIds: ['places'] },
    { words: ['Deutschland', 'Bier'], categoryIds: ['places', 'food_drinks'] },
    { words: ['Frankreich', 'Eiffelturm'], categoryIds: ['places'] },
    { words: ['Deutschland', 'Frankreich'], categoryIds: ['places'] },
    { words: ['London', 'Paris'], categoryIds: ['places'] },
    { words: ['Los Angeles', 'New York'], categoryIds: ['places'] },
    { words: ['Harvard', 'MIT'], categoryIds: ['places'] },
    { words: ['Oxford', 'Schule'], categoryIds: ['places'] },
    { words: ['Pyramide', 'Tempel'], categoryIds: ['places'] },
    { words: ['Burg', 'Haus'], categoryIds: ['places', 'general'] },

    // General
    { words: ['Auto', 'Bus'], categoryIds: ['general'] },
    { words: ['Rucksack', 'Koffer'], categoryIds: ['general'] },
    { words: ['Whirlpool', 'Sauna'], categoryIds: ['general'] },
    { words: ['Turnschuhe', 'Sandalen'], categoryIds: ['general'] },
    { words: ['Sonnenbrille', 'Taucherbrille'], categoryIds: ['general'] },
    { words: ['Klavier', 'Gitarre'], categoryIds: ['general', 'entertainment'] },
    { words: ['Kreuzfahrt', 'Safari'], categoryIds: ['general'] },
    { words: ['Virus', 'Bakterien'], categoryIds: ['general'] },
    { words: ['Auto', 'Fahrrad'], categoryIds: ['general'] },
    { words: ['Bleistift', 'Kugelschreiber'], categoryIds: ['general'] },
    { words: ['Arzt', 'Chirurg'], categoryIds: ['general'] },
    { words: ['Bombe', 'Gewehr'], categoryIds: ['general'] },
    { words: ['Hemd', 'Pullover'], categoryIds: ['general'] },
    { words: ['Uhr', 'Ring'], categoryIds: ['general'] },
    { words: ['Flugzeug', 'Hubschrauber'], categoryIds: ['general'] },
    { words: ['Lehrer', 'Professor'], categoryIds: ['general'] },
    { words: ['Messer', 'Schere'], categoryIds: ['general'] },
    { words: ['Stuhl', 'Bank'], categoryIds: ['general'] },
    { words: ['Zug', 'U-Bahn'], categoryIds: ['general'] },
    { words: ['Spiegel', 'Fensterscheibe'], categoryIds: ['general'] },
    { words: ['Schaufel', 'Axt'], categoryIds: ['general'] },
    { words: ['Küchentheke', 'Küchenchef'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Detektiv', 'Verbrecher'], categoryIds: ['general'] },
    { words: ['Uhr', 'Armbanduhr'], categoryIds: ['general'] },
    { words: ['Gemälde', 'Skizze'], categoryIds: ['general', 'entertainment'] },
    { words: ['Regenschirm', 'Sonnenschirm'], categoryIds: ['general'] },
    { words: ['Anzug', 'Krawatte'], categoryIds: ['general'] },
    { words: ['Socken', 'Strumpfhosen'], categoryIds: ['general'] },
    { words: ['Gürtel', 'Jeans'], categoryIds: ['general'] },
    { words: ['Krone', 'Hut'], categoryIds: ['general'] },
    { words: ['Kerze', 'Laterne'], categoryIds: ['general'] },
    { words: ['Bibliothek', 'Universität'], categoryIds: ['general', 'places'] },
    { words: ['Museum', 'Galerie'], categoryIds: ['general', 'places'] },
    { words: ['Kugelschreiber', 'Blatt Papier'], categoryIds: ['general'] },
    { words: ['Mond', 'Sonne'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Aufzug', 'Rolltreppe'], categoryIds: ['general'] },
    { words: ['Fähre', 'Kreuzfahrt'], categoryIds: ['general'] },
    { words: ['Karte', 'GPS'], categoryIds: ['general', 'technology'] },
    { words: ['Segelboot', 'Yacht'], categoryIds: ['general'] },
    { words: ['Meteor', 'Satellit'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Planet', 'Stern'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Erdbeben', 'Tsunami'], categoryIds: ['general', 'nature_animals'] },
    { words: ['CIA', 'FBI'], categoryIds: ['general'] },
    { words: ['Auto', 'LKW'], categoryIds: ['general'] },
    { words: ['Brücke', 'Tunnel'], categoryIds: ['general', 'places'] },
    { words: ['Bus', 'Straßenbahn'], categoryIds: ['general'] },
    { words: ['Zug', 'Bus'], categoryIds: ['general'] },
    { words: ['Boot', 'U-Boot'], categoryIds: ['general'] },
    { words: ['Notizbuch', 'Tagebuch'], categoryIds: ['general'] },
    { words: ['Löffel', 'Gabel'], categoryIds: ['general'] },
    { words: ['Bäckerei', 'Metzgerei'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Teller', 'Schüssel'], categoryIds: ['general'] },
    { words: ['Gold', 'Silber'], categoryIds: ['general'] },
    { words: ['Platin', 'Gold'], categoryIds: ['general'] },
    { words: ['Jacke', 'Mantel'], categoryIds: ['general'] },
    { words: ['Schal', 'Krawatte'], categoryIds: ['general'] },
    { words: ['Stiefel', 'Turnschuhe'], categoryIds: ['general'] },
    { words: ['Helm', 'Hut'], categoryIds: ['general'] },
    { words: ['Halskette', 'Armband'], categoryIds: ['general'] },
    { words: ['Ring', 'Ohrring'], categoryIds: ['general'] },
    { words: ['Mikrofon', 'Lautsprecher'], categoryIds: ['general', 'technology'] },
    { words: ['Kopfhörer', 'Ohrstöpsel'], categoryIds: ['general', 'technology'] },
    { words: ['Fernseher', 'Radio'], categoryIds: ['general', 'technology'] },
    { words: ['Projektor', 'Leinwand'], categoryIds: ['general', 'technology'] },
    { words: ['Taschenrechner', 'Schreibmaschine'], categoryIds: ['general', 'technology'] },
    { words: ['Taschenlampe', 'Laterne'], categoryIds: ['general'] },
    { words: ['Zelt', 'Hütte'], categoryIds: ['general'] },
    { words: ['Kompass', 'Karte'], categoryIds: ['general'] },
    { words: ['Bordkarte', 'Ausweis'], categoryIds: ['general'] },
    { words: ['Ticket', 'Rechnung'], categoryIds: ['general'] },
    { words: ['Reisepass', 'Ticket'], categoryIds: ['general'] },
    { words: ['U-Bahn', 'Taxi'], categoryIds: ['general'] },
    { words: ['Himmel', 'Jet'], categoryIds: ['general'] },
    { words: ['Motorrad', 'Roller'], categoryIds: ['general'] },
    { words: ['Apotheker', 'Arzt'], categoryIds: ['general'] },
    { words: ['Ingenieur', 'Architekt'], categoryIds: ['general'] },
    { words: ['Feuerwehrmann', 'Polizist'], categoryIds: ['general'] },
    { words: ['Pilot', 'Astronaut'], categoryIds: ['general'] },
    { words: ['Richter', 'Strafe'], categoryIds: ['general'] },
    { words: ['Bäcker', 'Koch'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Bauer', 'Fischer'], categoryIds: ['general'] },
    { words: ['Schmied', 'Zimmermann'], categoryIds: ['general'] },
    { words: ['Himmel', 'Hölle'], categoryIds: ['general'] },
    { words: ['Himmel', 'Wolken'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Film', 'Schauspieler'], categoryIds: ['general', 'entertainment'] },
    { words: ['Leinwand', 'Fernseher'], categoryIds: ['general', 'technology'] },
    { words: ['UFO', 'Drohnen'], categoryIds: ['general', 'technology'] },
    { words: ['Gott', 'Himmel'], categoryIds: ['general'] },
    { words: ['Schrank', 'Vitrine'], categoryIds: ['general'] },
    { words: ['Heizung', 'Föhn'], categoryIds: ['general'] },
    { words: ['Lampe', 'Kerze'], categoryIds: ['general'] },
    { words: ['Kissen', 'Decke'], categoryIds: ['general'] },
    { words: ['Ofen', 'Mikrowelle'], categoryIds: ['general', 'technology'] },
    { words: ['Pfanne', 'Topf'], categoryIds: ['general'] },
    { words: ['Treppe', 'Aufzug'], categoryIds: ['general'] },
    { words: ['Fenster', 'Tür'], categoryIds: ['general'] },
    { words: ['Ofen', 'Heizung'], categoryIds: ['general'] },
    { words: ['Armbanduhr', 'Wecker'], categoryIds: ['general'] },
    { words: ['Bett', 'Sofa'], categoryIds: ['general'] },
    { words: ['Buch', 'Zeitung'], categoryIds: ['general'] },
    { words: ['Wald', 'Park'], categoryIds: ['general', 'places', 'nature_animals'] },
    { words: ['Kino', 'Bowling'], categoryIds: ['general', 'entertainment'] },
    { words: ['Schwimmbad', 'Strand'], categoryIds: ['general', 'places'] },
    { words: ['Glas', 'Tasse'], categoryIds: ['general'] },
    { words: ['Job', 'Hobby'], categoryIds: ['general'] },
    { words: ['Jesus', 'Weihnachtsmann'], categoryIds: ['general'] },
    { words: ['BH', 'Bikini'], categoryIds: ['general'] },
];

export default WORD_PAIRS_DE;