import type { WordPair } from './wordPairCategories';

/**
 * English word pairs with category assignments.
 * Each pair can belong to multiple categories.
 */
export const WORD_PAIRS_EN: WordPair[] = [
    // Food & Drinks
    { words: ['Pizza', 'Burger'], categoryIds: ['food_drinks'] },
    { words: ['Coffee', 'Tea'], categoryIds: ['food_drinks'] },
    { words: ['sushi', 'pizza'], categoryIds: ['food_drinks'] },
    { words: ['hamburger', 'hotdog'], categoryIds: ['food_drinks'] },
    { words: ['chocolate', 'vanilla'], categoryIds: ['food_drinks'] },
    { words: ['beer', 'wine'], categoryIds: ['food_drinks'] },
    { words: ['whiskey', 'vodka'], categoryIds: ['food_drinks'] },
    { words: ['milk', 'juice'], categoryIds: ['food_drinks'] },
    { words: ['bread', 'butter'], categoryIds: ['food_drinks'] },
    { words: ['rice', 'pasta'], categoryIds: ['food_drinks'] },
    { words: ['chicken', 'beef'], categoryIds: ['food_drinks'] },
    { words: ['salt', 'pepper'], categoryIds: ['food_drinks'] },
    { words: ['sugar', 'honey'], categoryIds: ['food_drinks'] },
    { words: ['water', 'soda'], categoryIds: ['food_drinks'] },
    { words: ['Pancake', 'Doughnut'], categoryIds: ['food_drinks'] },
    { words: ['Ice cream', 'Cake'], categoryIds: ['food_drinks'] },
    { words: ['Pizza', 'Pasta'], categoryIds: ['food_drinks'] },
    { words: ['Pizza', 'Lasagna'], categoryIds: ['food_drinks'] },
    { words: ['Tortilla', 'Taco'], categoryIds: ['food_drinks'] },
    { words: ['Baguette', 'Ciabatta'], categoryIds: ['food_drinks'] },
    { words: ['Hot Dog', 'Bratwurst'], categoryIds: ['food_drinks'] },
    { words: ['Energy Drink', 'Soda'], categoryIds: ['food_drinks'] },
    { words: ['Coconut milk', 'soy milk'], categoryIds: ['food_drinks'] },
    { words: ['Bread', 'Toast'], categoryIds: ['food_drinks'] },

    // Nature & Animals
    { words: ['Dog', 'Cat'], categoryIds: ['nature_animals'] },
    { words: ['Beach', 'Mountain'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Sun', 'Moon'], categoryIds: ['nature_animals'] },
    { words: ['Banana', 'Apple'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['apple', 'orange'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['banana', 'strawberry'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['carrot', 'broccoli'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['potato', 'tomato'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['onion', 'garlic'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Dog', 'Wolf'], categoryIds: ['nature_animals'] },
    { words: ['Apple', 'Pear'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Mouse', 'Rat'], categoryIds: ['nature_animals'] },
    { words: ['Cucumber', 'Zucchini'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Strawberry', 'Raspberry'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Banana', 'Plantain'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Coconut', 'Pineapple'], categoryIds: ['food_drinks', 'nature_animals'] },
    { words: ['Dragon', 'Dinosaur'], categoryIds: ['nature_animals', 'entertainment'] },
    { words: ['Volcano', 'Mountain'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Desert', 'Sand'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Cloud', 'Fog'], categoryIds: ['nature_animals'] },
    { words: ['Snow', 'Hail'], categoryIds: ['nature_animals'] },
    { words: ['Jungle', 'Forest'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Parrot', 'Crow'], categoryIds: ['nature_animals'] },
    { words: ['Bat', 'Owl'], categoryIds: ['nature_animals'] },
    { words: ['Wolf', 'Fox'], categoryIds: ['nature_animals'] },
    { words: ['River', 'Lake'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Ocean', 'River'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Tiger', 'Cheetah'], categoryIds: ['nature_animals'] },
    { words: ['Shark', 'Dolphin'], categoryIds: ['nature_animals'] },
    { words: ['Penguin', 'Seagull'], categoryIds: ['nature_animals'] },
    { words: ['Moon', 'Planet'], categoryIds: ['nature_animals'] },
    { words: ['Comet', 'Asteroid'], categoryIds: ['nature_animals'] },
    { words: ['Lake', 'Pond'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Giraffe', 'Zebra'], categoryIds: ['nature_animals'] },
    { words: ['Elephant', 'Rhino'], categoryIds: ['nature_animals'] },
    { words: ['Alligator', 'Crocodile'], categoryIds: ['nature_animals'] },
    { words: ['Oyster', 'Clam'], categoryIds: ['nature_animals'] },
    { words: ['Jellyfish', 'Octopus'], categoryIds: ['nature_animals'] },
    { words: ['Birch', 'Shrub'], categoryIds: ['nature_animals'] },
    { words: ['Fountain', 'Waterfall'], categoryIds: ['nature_animals', 'places'] },
    { words: ['Hawk', 'Vulture'], categoryIds: ['nature_animals'] },
    { words: ['Lizard', 'Gecko'], categoryIds: ['nature_animals'] },

    // Technology
    { words: ['Apple', 'Microsoft'], categoryIds: ['technology', 'brands'] },
    { words: ['Google', 'Facebook'], categoryIds: ['technology', 'brands'] },
    { words: ['Amazon', 'Netflix'], categoryIds: ['technology', 'brands', 'entertainment'] },
    { words: ['Laptop', 'Tablet'], categoryIds: ['technology'] },
    { words: ['Bitcoin', 'Ethereum'], categoryIds: ['technology'] },
    { words: ['Facebook', 'Instagram'], categoryIds: ['technology', 'brands'] },
    { words: ['iPhone', 'Samsung'], categoryIds: ['technology', 'brands'] },
    { words: ['PlayStation', 'Xbox'], categoryIds: ['technology', 'games'] },
    { words: ['Windows', 'MacOS'], categoryIds: ['technology'] },
    { words: ['YouTube', 'TikTok'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Twitch', 'Kick'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Spotify', 'Apple Music'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Reddit', 'Discord'], categoryIds: ['technology'] },
    { words: ['Instagram', 'Snapchat'], categoryIds: ['technology', 'brands'] },
    { words: ['ChatGPT', 'Gemini'], categoryIds: ['technology'] },
    { words: ['Laptop', 'Desktop'], categoryIds: ['technology'] },
    { words: ['Tablet', 'Smartphone'], categoryIds: ['technology'] },
    { words: ['Mouse', 'Keyboard'], categoryIds: ['technology'] },
    { words: ['TV', 'Laptop'], categoryIds: ['technology'] },
    { words: ['Microphone', 'Camera'], categoryIds: ['technology'] },
    { words: ['Twitch', 'Netflix'], categoryIds: ['technology', 'entertainment'] },
    { words: ['Twitter', 'Facebook'], categoryIds: ['technology', 'brands'] },
    { words: ['SpaceX', 'Tesla'], categoryIds: ['technology', 'brands'] },

    // Brands & Companies
    { words: ['Perfume', 'Deodorant'], categoryIds: ['brands', 'general'] },
    { words: ['Adidas', 'Nike'], categoryIds: ['brands', 'sports'] },
    { words: ['McDonalds', 'KFC'], categoryIds: ['brands', 'food_drinks'] },
    { words: ['Burger King', 'McDonald\'s'], categoryIds: ['brands', 'food_drinks'] },
    { words: ['Sony', 'Samsung'], categoryIds: ['brands', 'technology'] },
    { words: ['Mercedes', 'BMW'], categoryIds: ['brands'] },
    { words: ['Tesla', 'Porsche'], categoryIds: ['brands'] },
    { words: ['Ferrari', 'Lamborghini'], categoryIds: ['brands'] },
    { words: ['Coca-Cola', 'Pepsi'], categoryIds: ['brands', 'food_drinks'] },


    // Sports
    { words: ['Football', 'Basketball'], categoryIds: ['sports'] },
    { words: ['Soccer', 'Rugby'], categoryIds: ['sports'] },
    { words: ['Tennis', 'Badminton'], categoryIds: ['sports'] },
    { words: ['Skiing', 'Snow'], categoryIds: ['sports', 'nature_animals'] },
    { words: ['Swimming', 'Diving'], categoryIds: ['sports'] },
    { words: ['Running', 'Jogging'], categoryIds: ['sports'] },
    { words: ['Bicycle', 'Motorcycle'], categoryIds: ['sports', 'general'] },
    { words: ['Boxing', 'Karate'], categoryIds: ['sports'] },
    { words: ['Hockey', 'Soccer'], categoryIds: ['sports'] },
    { words: ['Bowling', 'Golf'], categoryIds: ['sports'] },
    { words: ['Marathon', 'Sprint'], categoryIds: ['sports'] },
    { words: ['Fencing', 'Archery'], categoryIds: ['sports'] },
    { words: ['Volleyball', 'Basketball'], categoryIds: ['sports'] },
    { words: ['Table tennis', 'Badminton'], categoryIds: ['sports'] },
    { words: ['Baseball', 'Football'], categoryIds: ['sports'] },
    { words: ['Surfboard', 'Skateboard'], categoryIds: ['sports'] },
    { words: ['Golf', 'Cricket'], categoryIds: ['sports'] },
    { words: ['UFC', 'WWE'], categoryIds: ['sports', 'entertainment'] },
    { words: ['Olympics', 'World Cup'], categoryIds: ['sports'] },
    { words: ['NBA', 'NFL'], categoryIds: ['sports'] },
    { words: ['Bayern Munich', 'Real Madrid'], categoryIds: ['sports'] },

    // Entertainment
    { words: ['Lord of the rings', 'Hobbit'], categoryIds: ['entertainment'] },
    { words: ['Harry Potter', 'Lord Voldemort'], categoryIds: ['entertainment'] },
    { words: ['Superman', 'Batman'], categoryIds: ['entertainment'] },
    { words: ['Spiderman', 'Ironman'], categoryIds: ['entertainment'] },
    { words: ['Captain America', 'Thor'], categoryIds: ['entertainment'] },
    { words: ['Music', 'Dancing'], categoryIds: ['entertainment'] },
    { words: ['Ghost', 'Zombie'], categoryIds: ['entertainment'] },
    { words: ['Ballet', 'Hip Hop'], categoryIds: ['entertainment'] },
    { words: ['Radio', 'Podcast'], categoryIds: ['entertainment', 'technology'] },
    { words: ['online news', 'Newspaper'], categoryIds: ['entertainment'] },
    { words: ['Concert', 'Festival'], categoryIds: ['entertainment'] },
    { words: ['Netflix', 'Cinema'], categoryIds: ['entertainment'] },
    { words: ['Game of Thrones', 'Lord of the Rings'], categoryIds: ['entertainment'] },
    { words: ['Star Wars', 'Star Trek'], categoryIds: ['entertainment'] },
    { words: ['Harry Potter', 'Percy Jackson'], categoryIds: ['entertainment'] },
    { words: ['Sherlock Holmes', 'Hercule Poirot'], categoryIds: ['entertainment'] },
    { words: ['Dracula', 'Frankenstein'], categoryIds: ['entertainment'] },
    { words: ['James Bond', 'Secret Service'], categoryIds: ['entertainment'] },
    { words: ['Homer Simpson', 'Peter Griffin'], categoryIds: ['entertainment'] },
    { words: ['SpongeBob', 'Patrick'], categoryIds: ['entertainment'] },
    { words: ['Godzilla', 'King Kong'], categoryIds: ['entertainment'] },
    { words: ['Techno', 'Rap'], categoryIds: ['entertainment'] },
    { words: ['Rock', 'Pop'], categoryIds: ['entertainment'] },
    { words: ['Novel', 'Poem'], categoryIds: ['entertainment'] },
    { words: ['Dictionary', 'Encyclopedia'], categoryIds: ['entertainment', 'general'] },
    { words: ['Thor', 'Lightning'], categoryIds: ['entertainment'] },
    { words: ['Obi Wan', 'Force'], categoryIds: ['entertainment'] },

    // Famous People
    { words: ['Einstein', 'Newton'], categoryIds: ['famous_people'] },
    { words: ['Elvis', 'The Beatles'], categoryIds: ['famous_people', 'entertainment'] },
    { words: ['Leonardo da Vinci', 'Michelangelo'], categoryIds: ['famous_people'] },
    { words: ['Napoleon', 'Caesar'], categoryIds: ['famous_people'] },
    { words: ['Hitler', 'Stalin'], categoryIds: ['famous_people'] },
    { words: ['Picasso', 'Van Gogh'], categoryIds: ['famous_people'] },
    { words: ['Mozart', 'Beethoven'], categoryIds: ['famous_people', 'entertainment'] },
    { words: ['Messi', 'Ronaldo'], categoryIds: ['famous_people', 'sports'] },

    // Games
    { words: ['Mario', 'Luigi'], categoryIds: ['games', 'entertainment'] },
    { words: ['Sonic', 'Tails'], categoryIds: ['games', 'entertainment'] },
    { words: ['Pac-Man', 'Tetris'], categoryIds: ['games'] },
    { words: ['Fortnite', 'Minecraft'], categoryIds: ['games'] },
    { words: ['Call of Duty', 'Battlefield'], categoryIds: ['games'] },
    { words: ['Lego', 'Playmobil'], categoryIds: ['games'] },
    { words: ['UNO', 'Monopoly'], categoryIds: ['games'] },
    { words: ['Catan', 'Risk'], categoryIds: ['games'] },
    { words: ['Blackjack', 'Poker'], categoryIds: ['games'] },
    { words: ['Bingo', 'Roulette'], categoryIds: ['games'] },
    { words: ['Puzzle', 'Crossword'], categoryIds: ['games'] },
    { words: ['Cards', 'Dice'], categoryIds: ['games'] },

    // Places
    { words: ['New York', 'Los Angeles'], categoryIds: ['places'] },
    { words: ['Paris', 'London'], categoryIds: ['places'] },
    { words: ['Rome', 'Athens'], categoryIds: ['places'] },
    { words: ['Sydney', 'Melbourne'], categoryIds: ['places'] },
    { words: ['Rio de Janeiro', 'Buenos Aires'], categoryIds: ['places'] },
    { words: ['Mount Everest', 'Nepal'], categoryIds: ['places'] },
    { words: ['Amazon', 'Nile'], categoryIds: ['places', 'nature_animals'] },
    { words: ['Grand Canyon', 'Niagara Falls'], categoryIds: ['places'] },
    { words: ['Taj Mahal', 'Great Wall of China'], categoryIds: ['places'] },
    { words: ['Eiffel Tower', 'Statue of Liberty'], categoryIds: ['places'] },
    { words: ['Big Ben', 'Leaning Tower of Pisa'], categoryIds: ['places'] },
    { words: ['Japan', 'China'], categoryIds: ['places'] },
    { words: ['Germany', 'Beer'], categoryIds: ['places', 'food_drinks'] },
    { words: ['France', 'Eiffel Tower'], categoryIds: ['places'] },
    { words: ['Germany', 'France'], categoryIds: ['places'] },
    { words: ['London', 'Paris'], categoryIds: ['places'] },
    { words: ['Los Angeles', 'New York'], categoryIds: ['places'] },
    { words: ['Harvard', 'MIT'], categoryIds: ['places'] },
    { words: ['Oxford', 'Highschool'], categoryIds: ['places'] },
    { words: ['Pyramid', 'Temple'], categoryIds: ['places'] },
    { words: ['Castle', 'House'], categoryIds: ['places', 'general'] },

    // General
    { words: ['Car', 'Bus'], categoryIds: ['general'] },
    { words: ['backpack', 'suitcase'], categoryIds: ['general'] },
    { words: ['jacuzzi', 'sauna'], categoryIds: ['general'] },
    { words: ['sneakers', 'sandals'], categoryIds: ['general'] },
    { words: ['sunglasses', 'eyeglasses'], categoryIds: ['general'] },
    { words: ['piano', 'guitar'], categoryIds: ['general', 'entertainment'] },
    { words: ['cruise', 'safari'], categoryIds: ['general'] },
    { words: ['virus', 'bacteria'], categoryIds: ['general'] },
    { words: ['Car', 'Bike'], categoryIds: ['general'] },
    { words: ['Pencil', 'Pen'], categoryIds: ['general'] },
    { words: ['Doctor', 'Surgeon'], categoryIds: ['general'] },
    { words: ['Bomb', 'Gun'], categoryIds: ['general'] },
    { words: ['Shirt', 'Sweater'], categoryIds: ['general'] },
    { words: ['Watch', 'Ring'], categoryIds: ['general'] },
    { words: ['Plane', 'Helicopter'], categoryIds: ['general'] },
    { words: ['Teacher', 'Professor'], categoryIds: ['general'] },
    { words: ['Knife', 'Scissors'], categoryIds: ['general'] },
    { words: ['Chair', 'Bench'], categoryIds: ['general'] },
    { words: ['Train', 'Bus'], categoryIds: ['general'] },
    { words: ['Mirror', 'window pane'], categoryIds: ['general'] },
    { words: ['Shovel', 'Axe'], categoryIds: ['general'] },
    { words: ['Chef', 'Kitchen counter'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Detective', 'Criminal'], categoryIds: ['general'] },
    { words: ['Clock', 'Watch'], categoryIds: ['general'] },
    { words: ['Painting', 'Sketch'], categoryIds: ['general', 'entertainment'] },
    { words: ['Umbrella', 'Parasol'], categoryIds: ['general'] },
    { words: ['Suit', 'necktie'], categoryIds: ['general'] },
    { words: ['Socks', 'Stockings'], categoryIds: ['general'] },
    { words: ['Belt', 'Jeans'], categoryIds: ['general'] },
    { words: ['Crown', 'Hat'], categoryIds: ['general'] },
    { words: ['Candle', 'Lantern'], categoryIds: ['general'] },
    { words: ['Library', 'University'], categoryIds: ['general', 'places'] },
    { words: ['Museum', 'Gallery'], categoryIds: ['general', 'places'] },
    { words: ['Pen', 'Paper'], categoryIds: ['general'] },
    { words: ['Moon', 'Sun'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Elevator', 'Escalator'], categoryIds: ['general'] },
    { words: ['Ferry', 'Cruise'], categoryIds: ['general'] },
    { words: ['Map', 'GPS'], categoryIds: ['general', 'technology'] },
    { words: ['Sailboat', 'Yacht'], categoryIds: ['general'] },
    { words: ['Meteor', 'Satellite'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Planet', 'Star'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Earthquake', 'Tsunami'], categoryIds: ['general', 'nature_animals'] },
    { words: ['CIA', 'FBI'], categoryIds: ['general'] },
    { words: ['Car', 'Truck'], categoryIds: ['general'] },
    { words: ['Bridge', 'Tunnel'], categoryIds: ['general', 'places'] },
    { words: ['Bus', 'Tram'], categoryIds: ['general'] },
    { words: ['Train', 'Monorail'], categoryIds: ['general'] },
    { words: ['Boat', 'Submarine'], categoryIds: ['general'] },
    { words: ['Notebook', 'Diary'], categoryIds: ['general'] },
    { words: ['Spoon', 'Fork'], categoryIds: ['general'] },
    { words: ['Bakery', 'Butcher'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Plate', 'Bowl'], categoryIds: ['general'] },
    { words: ['Gold', 'Silver'], categoryIds: ['general'] },
    { words: ['Platinum', 'Gold'], categoryIds: ['general'] },
    { words: ['Jacket', 'Coat'], categoryIds: ['general'] },
    { words: ['Scarf', 'Tie'], categoryIds: ['general'] },
    { words: ['Boots', 'Sneakers'], categoryIds: ['general'] },
    { words: ['Helmet', 'Hat'], categoryIds: ['general'] },
    { words: ['Necklace', 'Bracelet'], categoryIds: ['general'] },
    { words: ['Ring', 'Earring'], categoryIds: ['general'] },
    { words: ['Microphone', 'Speaker'], categoryIds: ['general', 'technology'] },
    { words: ['Headphones', 'Earbuds'], categoryIds: ['general', 'technology'] },
    { words: ['Television', 'Radio'], categoryIds: ['general', 'technology'] },
    { words: ['Projector', 'Screen'], categoryIds: ['general', 'technology'] },
    { words: ['Calculator', 'Typewriter'], categoryIds: ['general', 'technology'] },
    { words: ['Flashlight', 'Lantern'], categoryIds: ['general'] },
    { words: ['Tent', 'Cabin'], categoryIds: ['general'] },
    { words: ['Compass', 'Map'], categoryIds: ['general'] },
    { words: ['Boarding pass', 'ID card'], categoryIds: ['general'] },
    { words: ['Ticket', 'Invoice'], categoryIds: ['general'] },
    { words: ['Passport', 'Ticket'], categoryIds: ['general'] },
    { words: ['Subway', 'Taxi'], categoryIds: ['general'] },
    { words: ['Sky', 'Jet'], categoryIds: ['general'] },
    { words: ['Motorcycle', 'Scooter'], categoryIds: ['general'] },
    { words: ['Pharmacist', 'Doctor'], categoryIds: ['general'] },
    { words: ['Engineer', 'Architect'], categoryIds: ['general'] },
    { words: ['Firefighter', 'Policeman'], categoryIds: ['general'] },
    { words: ['Pilot', 'Astronaut'], categoryIds: ['general'] },
    { words: ['Judge', 'Punishment'], categoryIds: ['general'] },
    { words: ['Baker', 'Chef'], categoryIds: ['general', 'food_drinks'] },
    { words: ['Farmer', 'Fisherman'], categoryIds: ['general'] },
    { words: ['Blacksmith', 'Carpenter'], categoryIds: ['general'] },
    { words: ['Heaven', 'Hell'], categoryIds: ['general'] },
    { words: ['Sky', 'Clouds'], categoryIds: ['general', 'nature_animals'] },
    { words: ['Movie', 'Actor'], categoryIds: ['general', 'entertainment'] },
    { words: ['Screen', 'TV'], categoryIds: ['general', 'technology'] },
    { words: ['UFO', 'Drones'], categoryIds: ['general', 'technology'] },
    { words: ['God', 'Heaven'], categoryIds: ['general'] },
    { words: ['Wardrobe', 'Showcase'], categoryIds: ['general'] },
    { words: ['Radiator', 'Hairdryer'], categoryIds: ['general'] },
    { words: ['Lamp', 'Candle'], categoryIds: ['general'] },
    { words: ['Pillow', 'Blanket'], categoryIds: ['general'] },
    { words: ['Oven', 'Microwave'], categoryIds: ['general', 'technology'] },
    { words: ['Pan', 'Pot'], categoryIds: ['general'] },
    { words: ['Stairs', 'Elevator'], categoryIds: ['general'] },
    { words: ['Window', 'Door'], categoryIds: ['general'] },
    { words: ['Oven', 'Heating'], categoryIds: ['general'] },
    { words: ['Wristwatch', 'Alarm Clock'], categoryIds: ['general'] },
    { words: ['Bed', 'Sofa'], categoryIds: ['general'] },
    { words: ['Book', 'Newspaper'], categoryIds: ['general'] },
    { words: ['Forest', 'Park'], categoryIds: ['general', 'places', 'nature_animals'] },
    { words: ['Cinema', 'Bowling'], categoryIds: ['general', 'entertainment'] },
    { words: ['Swimming Pool', 'Beach'], categoryIds: ['general', 'places'] },
    { words: ['Glass', 'Cup'], categoryIds: ['general'] },
    { words: ['Job', 'Hobby'], categoryIds: ['general'] },
    { words: ['Jesus', 'Santa Claus'], categoryIds: ['general'] },
    { words: ['bra', 'bikini'], categoryIds: ['general'] },
    { words: ['Denim', 'Corduroy'], categoryIds: ['general'] },
];

export default WORD_PAIRS_EN;