version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: eslint
        update-types: ['version-update:semver-major']
      - dependency-name: '@eslint/js'
        update-types: ['version-update:semver-major']
    groups:
      capacitor:
        patterns: ['@capacitor/*', 'capacitor-*']
      mui:
        patterns: ['@mui/*']
      minor-and-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
