services:
  melodiq-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melodiq-server-dev
    restart: "no"
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config:z
      - ./models:/app/models:z
      - ./src:/app/src:z
      - ./music:/app/music:z
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MUSIC_DIR=/app/music
      - CONFIG_PATH=/app/config/config.json
      - ALLOWED_ORIGINS=*

